spring:
  application:
    name: ariza

  datasource:
    username: postgres
    password: postgre5432
    url: jdbc:postgresql://localhost:5432/ariza
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

